### ISSUE TITLE
Sport type selector is not legible on Windows in dark mode

### ISSUE THREAD

**Issue by unitbob1** [c-harding/heatmapper#67]
When in dark mode, the text in the sports type selector is white till it is hovered over, when the blue background makes it legible. 
![image](https://github.com/c-harding/heatmapper/assets/61231944/409dac71-5e77-47ef-9025-4fdfdb26a3f8)

**Comment by unitbob1** [comment]
Occurs both in activity map and heatmapper

**Comment by c-harding** [comment]
Possible fix for Dropdown.vue:

```css
select option {
  background-color: var(--background);
  color: var(--color);
}
```
